[package]
name = "utils"
version = "0.1.0"
authors = ["John Barker <dev@j16r.net>"]

[features]
default = ["std"]
std = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
